version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo installing dependencies ...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - REACT_APP_API_URL=$REACT_APP_API_URL npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  base-directory:
    - 'build'
  files:
    - '**/*'
